# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1= np.array([1,2,3])

# Create a 2-dimensional NumPy array using np.array()
a2= np.array([[1,2,3],[4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3=np.array([[[1,2,3],[2,3,4]],
             [[5,6,7],[7,8,9]],
             [[8,9,0],[0,1,2]]]);

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape, a1.dtype, a1.size, type(a1)

((3,), dtype('int32'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a2.shape, a2.dtype, a2.size, type(a2)

((2, 3), dtype('int32'), 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
a3.shape, a3.dtype, a3.size, type(a3)

((3, 2, 3), dtype('int32'), 18, numpy.ndarray)

In [9]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd 
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [13]:
# Create an array of shape (10, 2) with only ones
a4= np.ones((10,2), int)
a4

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [15]:
# Create an array of shape (7, 2, 3) of only zeros
a5= np.zeros((7,2,3),int)
a5

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [17]:
# Create an array within a range of 0 and 100 with step 3
a6= np.arange(0,100,3)
a6

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [18]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
a7= np.random.randint(0,10,size=(7,2))
a7

array([[8, 5],
       [4, 8],
       [8, 1],
       [4, 2],
       [0, 4],
       [2, 5],
       [4, 8]])

In [21]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
a8= np.random.random((3,5))
a8

array([[0.87713415, 0.85000229, 0.90392658, 0.59191001, 0.0700975 ],
       [0.16086233, 0.24049596, 0.41861397, 0.49912273, 0.02713033],
       [0.17822707, 0.16356824, 0.16226989, 0.38991943, 0.43724379]])

In [23]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
a9= np.random.randint(0,10,size=(4,6))
a9

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [24]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
a10 = np.random.randint(1,10,size=(3,7))
print(a10)

# Find the unique numbers in the array you just created
np.unique(a10)

[[9 1 3 7 4 9 3]
 [5 3 7 5 9 7 2]
 [4 9 2 9 5 2 4]]


array([1, 2, 3, 4, 5, 7, 9])

In [25]:
# Find the 0'th index of the latest array you created
a10[0]

array([9, 1, 3, 7, 4, 9, 3])

In [28]:
# Get the first 2 rows of latest array you created
a10[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [29]:
# Get the first 2 values of the first 2 rows of the latest array
a10[:2, :2]

array([[9, 1],
       [5, 3]])

In [36]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
a11= np.random.randint(0,10,size=(3,5))
a12= np.ones((3,5),int)
a11,a12

(array([[9, 6, 9, 8, 6],
        [8, 7, 1, 0, 6],
        [6, 7, 4, 2, 7]]),
 array([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]))

In [37]:
# Add the two arrays together
a11+a12

array([[10,  7, 10,  9,  7],
       [ 9,  8,  2,  1,  7],
       [ 7,  8,  5,  3,  8]])

In [38]:
# Create another array of ones of shape (5, 3)
a13= np.ones((5,3))

In [41]:
# Try add the array of ones and the other most recent array together
#a12+a13
#error = operands could not be broadcast together with shapes (3,5) (5,3) 


#sol;

a12+ a13.T

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [43]:
# Create another array of ones of shape (3, 5)
a14= np.ones((3,5))

In [45]:
# Subtract the new array of ones from the other most recent array
a14-a13

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [48]:
# Multiply the ones array with the latest array
a11*a14

array([[9., 6., 9., 8., 6.],
       [8., 7., 1., 0., 6.],
       [6., 7., 4., 2., 7.]])

In [49]:
# Take the latest array to the power of 2 using '**'
a11**2

array([[81, 36, 81, 64, 36],
       [64, 49,  1,  0, 36],
       [36, 49, 16,  4, 49]])

In [50]:
# Do the same thing with np.square()
np.square(a11)

array([[81, 36, 81, 64, 36],
       [64, 49,  1,  0, 36],
       [36, 49, 16,  4, 49]])

In [51]:
# Find the mean of the latest array using np.mean()
np.mean(a11)

5.733333333333333

In [52]:
# Find the maximum of the latest array using np.max()
np.max(a11)

9

In [53]:
# Find the minimum of the latest array using np.min()
np.min(a11)

0

In [54]:
# Find the standard deviation of the latest array
np.std(a11)

2.6948510575210314

In [55]:
# Find the variance of the latest array
np.var(a11)

7.2622222222222215

In [56]:
# Reshape the latest array to (3, 5, 1)
a11.reshape(3,5,1)

array([[[9],
        [6],
        [9],
        [8],
        [6]],

       [[8],
        [7],
        [1],
        [0],
        [6]],

       [[6],
        [7],
        [4],
        [2],
        [7]]])

In [59]:
# Transpose the latest array
a14.T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

What does the transpose do?

In [60]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
a15= np.random.randint(0,10,size=(3,3))
a16= np.random.randint(0,10,size=(3,2))

In [61]:
# Perform a dot product on the two newest arrays you created
np.dot(a15,a16)

array([[ 46,  48],
       [ 62,  52],
       [113,  54]])

In [62]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
a17= np.random.randint(0,10,size=(4,3))
a18= np.random.randint(0,10,size=(4,3))

In [63]:
# Perform a dot product on the two newest arrays you created
np.dot(a17,a18)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [66]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
a17= a17.T
np.dot(a17, a18)

array([[105, 105, 103],
       [ 38,  36,  94],
       [ 93,  90, 110]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [67]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
a19= np.random.randint(0,10,size=(4,3))
a20= np.random.randint(0,10,size=(4,3))

In [68]:
# Compare the two arrays with '>'
a19>a20

array([[ True, False,  True],
       [False,  True,  True],
       [ True, False,  True],
       [False,  True,  True]])

What happens when you compare the arrays with `>`?

In [69]:
# Compare the two arrays with '>='
a19>=a20

array([[ True, False,  True],
       [False,  True,  True],
       [ True, False,  True],
       [False,  True,  True]])

In [70]:
# Find which elements of the first array are greater than 7
a19>7

array([[ True, False,  True],
       [False, False, False],
       [False,  True, False],
       [False, False,  True]])

In [71]:
# Which parts of each array are equal? (try using '==')
a19 == a20

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [72]:
# Sort one of the arrays you just created in ascending order
np.sort(a20)

array([[5, 7, 7],
       [0, 3, 8],
       [0, 3, 9],
       [1, 2, 6]])

In [73]:
# Sort the indexes of one of the arrays you just created
np.argsort(a20)

array([[1, 0, 2],
       [2, 1, 0],
       [0, 2, 1],
       [1, 2, 0]], dtype=int64)

In [74]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(a20)

7

In [75]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(a20)

5

In [76]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argsort(a20,axis=1)

array([[1, 0, 2],
       [2, 1, 0],
       [0, 2, 1],
       [1, 2, 0]], dtype=int64)

In [77]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argsort(a20,axis=0)

array([[2, 3, 1],
       [3, 1, 3],
       [0, 0, 2],
       [1, 2, 0]], dtype=int64)

In [79]:
# Create an array of normally distributed random numbers
mean = 0
std_dev = 1
array_size = 1000  # You can change this to any number

# Generate normally distributed random numbers
random_numbers = np.random.normal(loc=mean, scale=std_dev, size=array_size)
random_numbers

array([-1.07666051e+00,  6.68407961e-01, -1.08959310e+00,  1.63112585e+00,
       -7.71628322e-01,  2.96628320e-01,  1.00514257e+00, -2.52380043e-01,
        3.40600019e-01,  1.43518155e+00,  5.64402988e-01,  3.55550630e-01,
       -1.68478539e+00, -9.33722253e-01,  1.04692013e+00,  5.69950305e-01,
        7.21466274e-01,  6.35396932e-01,  1.28975653e+00, -2.61399925e-01,
        1.20499959e-01, -1.02867433e+00, -1.27802258e+00, -1.64374072e+00,
       -8.85163499e-01,  1.55256182e+00, -1.55272707e+00, -3.03535986e-01,
       -1.29314532e+00, -6.00973963e-01,  1.69693792e-01, -7.00115873e-01,
        1.08966487e+00,  1.53397812e+00, -2.24909573e+00, -6.82992330e-01,
        5.91421223e-02,  1.12611703e+00, -4.54244275e-01, -1.99353952e-02,
       -1.15674423e+00, -1.53279585e+00,  1.44538469e+00, -1.82406987e+00,
        2.32861901e+00,  7.25151399e-01,  6.79973076e-01,  5.75468667e-01,
       -2.52685688e-01,  3.92084530e-01, -1.88896688e-01,  5.53073276e-01,
       -3.36865269e-02, -

In [85]:
# Create an array with 10 evenly spaced numbers between 1 and 100
a21= np.linspace(1,100,10)
a21

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.