# intro to scikit-learn (sklearn)

![MLpng](ML.png)

# 0. Workflow

In [44]:
import pandas as pd
import numpy as np
from scikit
heart= pd.read_csv("data/heart-disease.csv")
heart

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

## 1. get the data ready

In [7]:
# x is feature matric
x = heart.drop("target",axis=1)

#y label/output
y= heart["target"]

## 2. choose the right model

In [10]:
from sklearn.ensemble import RandomForestClassifier
clf= RandomForestClassifier()

clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

## 3. fit the model to data

In [11]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=0.2)

In [18]:
clf.fit(x_train, y_train);

In [19]:
x_train

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
191   58    1   0       128   216    0        0      131      1      2.2   
49    53    0   0       138   234    0        0      160      0      0.0   
40    51    0   2       140   308    0        0      142      0      1.5   
129   74    0   1       120   269    0        0      121      1      0.2   
222   65    1   3       138   282    1        0      174      0      1.4   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
206   59    1   0       110   239    0        0      142      1      1.2   
121   59    1   0       138   271    0        0      182      0      0.0   
159   56    1   1       130   221    0        0      163      0      0.0   
209   59    1   0       140   177    0        1      162      1      0.0   
296   63    0   0       124   197    0        1      136      1      0.0   

     slope  ca  thal  
191      1   3     3  
49       2   0     2  
40       2   1     2  
129      2   1     2  
222      1   1     2  
..     ...  ..   ...  
206      1   1     3  
121      2   0     2  
159      2   0     3  
209      2   1     3  
296      1   0     2  

[242 rows x 13 columns]

In [17]:
# prediction
y_label=clf.predict(np.array([0,2,3,4]))

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


ValueError: Expected 2D array, got 1D array instead:
array=[0. 2. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [21]:
y_preds= clf.predict(x_test)
y_preds

array([0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1], dtype=int64)

In [22]:
y_test

201    0
228    0
150    1
113    1
71     1
      ..
19     1
290    0
267    0
127    1
67     1
Name: target, Length: 61, dtype: int64

## 4. evaluate model

In [23]:
clf.score(x_train, y_train)

1.0

In [24]:
clf.score(x_test, y_test)

0.8360655737704918

In [48]:
from sklearn.metrics import *
#classification_report, confusion_matrix, accuracy_score
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.79      0.85      0.81        26
           1       0.88      0.83      0.85        35

    accuracy                           0.84        61
   macro avg       0.83      0.84      0.83        61
weighted avg       0.84      0.84      0.84        61



In [28]:
print(confusion_matrix(y_test, y_preds))

[[22  4]
 [ 6 29]]


In [29]:
print(accuracy_score(y_test, y_preds))

0.8360655737704918


## 5. improve a model

In [34]:
np.random.seed(42)
for i in range(10,100,10):
    print(f"trying model with {i} estimators..")
    clf = RandomForestClassifier(n_estimators=i).fit(x_train,y_train)
    print(f"model accuray on test set: {clf.score(x_test,y_test)*100:.2f}%")
    print(" ")

trying model with 10 estimators..
model accuray on test set: 80.33%
 
trying model with 20 estimators..
model accuray on test set: 86.89%
 
trying model with 30 estimators..
model accuray on test set: 83.61%
 
trying model with 40 estimators..
model accuray on test set: 81.97%
 
trying model with 50 estimators..
model accuray on test set: 86.89%
 
trying model with 60 estimators..
model accuray on test set: 80.33%
 
trying model with 70 estimators..
model accuray on test set: 83.61%
 
trying model with 80 estimators..
model accuray on test set: 85.25%
 
trying model with 90 estimators..
model accuray on test set: 83.61%
 


## 6.save and load model

In [36]:
import pickle

pickle.dump(clf,open("random.pkl","wb"))

In [39]:
load = pickle.load(open("random.pkl","rb"))
load.score(x_test,y_test)

0.8360655737704918

![a](ML.png)

# 1. getting the data ready 

In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
%matplotlib inline

three task
1. split data into feature and labels
2. filling (imputing) missing values
3. converting non_numerical to numeircal values (feature enconding)

In [50]:
heart.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [56]:
# x is feature matric
x = heart.drop("target",axis=1)

#y label/output
y= heart["target"]

In [64]:
# spliting of data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.5)

In [65]:
x.shape, y.shape

((303, 13), (303,))

In [66]:
x_train.shape, x_test.shape

((151, 13), (152, 13))

In [67]:
y_train.shape, y_test.shape

((151,), (152,))

## 1.1 make sure data is numerical 

In [70]:
data= pd.read_csv("data/car-sales-extended.csv")
data.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [71]:
len(data)

1000

In [73]:
data.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [76]:
# split data 
x= data.drop("Price",axis=1)
y= data["Price"]

# split into training and test
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2)

In [77]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(x_train,y_train)
model.score(x_test,y_test)

ValueError: could not convert string to float: 'Honda'

In [92]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features= ["Make", "Colour", "Doors"]
one_hot= OneHotEncoder()
transformer= ColumnTransformer([("one_hot",
                                one_hot,
                                categorical_features)],
                              remainder="passthrough")


transformed_x= transformer.fit_transform(x)
transformed_x

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [93]:
pd.DataFrame(transformed_x)

0    1    2    3    4    5    6    7    8    9    10   11        12
0    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1    1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2    0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3    0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4    0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...       ...
995  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   35820.0
996  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  155144.0
997  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0   66604.0
998  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  215883.0
999  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  248360.0

[1000 rows x 13 columns]

In [95]:
# refit the model


# split into training and test
x_train,x_test,y_train,y_test= train_test_split(transformed_x,y,test_size=0.2)


model.fit(x_train,y_train)
model.score(x_test,y_test)


0.3872174308636126

## 1.2 missing value

1. miss them some value 
2. remove them

In [97]:
data1= pd.read_csv("data/car-sales-extended-missing-data.csv")

In [99]:
data1.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [104]:
x=data1.drop("Price",axis=1)
y=data1["Price"]
x

Make Colour  Odometer (KM)  Doors
0     Honda  White        35431.0    4.0
1       BMW   Blue       192714.0    5.0
2     Honda  White        84714.0    4.0
3    Toyota  White       154365.0    4.0
4    Nissan   Blue       181577.0    3.0
..      ...    ...            ...    ...
995  Toyota  Black        35820.0    4.0
996     NaN  White       155144.0    3.0
997  Nissan   Blue        66604.0    4.0
998   Honda  White       215883.0    4.0
999  Toyota   Blue       248360.0    4.0

[1000 rows x 4 columns]

In [103]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features= ["Make", "Colour", "Doors"]
one_hot= OneHotEncoder()
transformer= ColumnTransformer([("one_hot",
                                one_hot,
                                categorical_features)],
                              remainder="passthrough")


transformed_x= transformer.fit_transform(x)
transformed_x

<1000x16 sparse matrix of type '<class 'numpy.float64'>'
	with 4000 stored elements in Compressed Sparse Row format>

### fill missing data with pandas

In [107]:
# fill the make column
data1["Make"].fillna("missing", inplace=True)

data1["Colour"].fillna("missing", inplace=True)

data1["Odometer (KM)"].fillna(data1["Odometer (KM)"].mean, inplace=True)

data1["Doors"].fillna(4, inplace=True)

In [108]:
data1.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [109]:
data1= data1.dropna()

In [110]:
data1.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [114]:
len(data1)

950

In [118]:
x=data1.drop("Price",axis=1)
y=data1["Price"]
x

Make Colour Odometer (KM)  Doors
0      Honda  White       35431.0    4.0
1        BMW   Blue      192714.0    5.0
2      Honda  White       84714.0    4.0
3     Toyota  White      154365.0    4.0
4     Nissan   Blue      181577.0    3.0
..       ...    ...           ...    ...
995   Toyota  Black       35820.0    4.0
996  missing  White      155144.0    3.0
997   Nissan   Blue       66604.0    4.0
998    Honda  White      215883.0    4.0
999   Toyota   Blue      248360.0    4.0

[950 rows x 4 columns]

In [119]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features= ["Make", "Colour", "Doors"]
one_hot= OneHotEncoder()
transformer= ColumnTransformer([("one_hot",
                                one_hot,
                                categorical_features)],
                              remainder="passthrough")


transformed_x= transformer.fit_transform(data1)
transformed_x

array([[0.0, 1.0, 0.0, ..., 0.0, 35431.0, 15323.0],
       [1.0, 0.0, 0.0, ..., 1.0, 192714.0, 19943.0],
       [0.0, 1.0, 0.0, ..., 0.0, 84714.0, 28343.0],
       ...,
       [0.0, 0.0, 1.0, ..., 0.0, 66604.0, 31570.0],
       [0.0, 1.0, 0.0, ..., 0.0, 215883.0, 4001.0],
       [0.0, 0.0, 0.0, ..., 0.0, 248360.0, 12732.0]], dtype=object)

### seocond method for fill missing data with pandas

In [120]:
data2= pd.read_csv("data/car-sales-extended-missing-data.csv")

In [121]:
data2.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [122]:
data2.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [124]:
data2.dropna(subset=["Price"],inplace=True)

In [125]:
data2.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [126]:
x= data2.drop("Price",axis=1)
y=data2["Price"]

In [129]:
# fill missing values using scikit learn 
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

cat_imputer= SimpleImputer(strategy="constant", fill_value="missing")
door_imputer= SimpleImputer(strategy="constant", fill_value=4)
num_imputer= SimpleImputer(strategy="mean")

cat=["Make", "Colour"]
door=["Doors"]
num=["Odometer (KM)"]

imputer= ColumnTransformer([
    ("cat_imputer", cat_imputer, cat),
    ("door_imputer", door_imputer, door),
    ("num_imputer", num_imputer, num)
])

filled_x= imputer.fit_transform(x)
filled_x

array([['Honda', 'White', 4.0, 35431.0],
       ['BMW', 'Blue', 5.0, 192714.0],
       ['Honda', 'White', 4.0, 84714.0],
       ...,
       ['Nissan', 'Blue', 4.0, 66604.0],
       ['Honda', 'White', 4.0, 215883.0],
       ['Toyota', 'Blue', 4.0, 248360.0]], dtype=object)

In [131]:
data3= pd.DataFrame(filled_x, columns=["Make","Colour", "Doors", "Odometer (KM)"])
data3.head()

Make Colour Doors Odometer (KM)
0   Honda  White   4.0       35431.0
1     BMW   Blue   5.0      192714.0
2   Honda  White   4.0       84714.0
3  Toyota  White   4.0      154365.0
4  Nissan   Blue   3.0      181577.0

In [134]:
data3.isna().sum()

Make             0
Colour           0
Doors            0
Odometer (KM)    0
dtype: int64

In [135]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features= ["Make", "Colour", "Doors"]
one_hot= OneHotEncoder()
transformer= ColumnTransformer([("one_hot",
                                one_hot,
                                categorical_features)],
                              remainder="passthrough")


transformed_x= transformer.fit_transform(data3)
transformed_x

<950x15 sparse matrix of type '<class 'numpy.float64'>'
	with 3800 stored elements in Compressed Sparse Row format>